setw -g mode-keys vi
set -g mouse on
bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "xclip -selection clipboard -in"
set-option -g history-limit 50000

set -g prefix C-a
unbind-key C-b
bind C-a send-prefix

bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

bind-key -r H resize-pane -L "5"
bind-key -r J resize-pane -D "5"
bind-key -r K resize-pane -U "5"
bind-key -r L resize-pane -R "5"

set-option -g allow-rename off
set-option -sg escape-time 100 # for win openssh beta

set-environment -g SSH_AUTH_SOCK "$HOME/.ssh/ssh_auth_sock"
set-option -g update-environment "DISPLAY SSH_ASKPASS SSH_AGENT_PID SSH_CONNECTION WINDOWID XAUTHORITY"

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin "janoamaral/tokyo-night-tmux"
set -g @tokyo-night-tmux_theme night
set -g @tokyo-night-tmux_transparent 1

run '~/.tmux/plugins/tpm/tpm'
